# -*- coding: utf-8 -*-
"""analise_eneva.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fbTfxCWfaIkgzHARD3Odoq_X1j99qHQ
"""

!pip install xlsxwriter

import logging
import requests
import pandas as pd
import calendar
import time
import matplotlib.pyplot as plt


# ==============================================================================
# REQUISITO 2: ESTRUTURA E ORGANIZAÇÃO (CONFIGURAÇÃO DE LOGS)
# ==============================================================================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("log.txt", mode='w', encoding='utf-8'),
        logging.StreamHandler()
    ]
)

logging.info("Iniciando o pipeline de dados: Projeto Eneva 2026.")

# ==============================================================================
# BLOCO DE FUNÇÕES AUXILIARES
# ==============================================================================

def buscar_dados_ons(data_inicio, data_fim, area_carga):
    """
    Função responsável por conectar na API do ONS e extrair os dados.
    Lógica: Monta a URL parametrizada, executa o GET e converte o JSON em DataFrame.
    """
    url_base = "https://apicarga.ons.org.br/prd/cargaverificada"
    parametros = {
        "dat_inicio": data_inicio,
        "dat_fim": data_fim,
        "cod_areacarga": area_carga
    }

    try:
        resposta = requests.get(url_base, params=parametros)
        logging.info(f"API Request [{area_carga} | {data_inicio} a {data_fim}] - Status: {resposta.status_code}")

        if resposta.status_code == 200:
            return pd.DataFrame(resposta.json())
        else:
            logging.error(f"Erro na API. Resposta: {resposta.text}")
            return None
    except Exception as e:
        logging.error(f"Falha de conexão: {e}")
        return None

def classificar_estacao(data):
    """ Classificação sazonal para o Hemisfério Sul. """
    dia_mes = (data.month, data.day)
    if (3, 20) <= dia_mes < (6, 21): return 'Outono'
    elif (6, 21) <= dia_mes < (9, 23): return 'Inverno'
    elif (9, 23) <= dia_mes < (12, 21): return 'Primavera'
    else: return 'Verão'

# ==============================================================================
# PASSO 1: EXTRAÇÃO DE DADOS (PAGINAÇÃO)
# ==============================================================================
anos_solicitados = [2021, 2022, 2023]
subsistemas = ['SECO', 'S', 'NE', 'N']
tabelas_extraidas = []

logging.info("Iniciando extração. Lógica: Paginação mensal para evitar bloqueio da API.")

for ano in anos_solicitados:
    for sub in subsistemas:
        for mes in range(1, 13):
            ultimo_dia = calendar.monthrange(ano, mes)[1]
            data_inicio = f"{ano}-{mes:02d}-01"
            data_fim = f"{ano}-{mes:02d}-{ultimo_dia:02d}"

            df_temp = buscar_dados_ons(data_inicio, data_fim, area_carga=sub)
            if df_temp is not None and not df_temp.empty:
                tabelas_extraidas.append(df_temp)

            time.sleep(0.5)

# Trava de segurança inserida: Verifica se a lista está vazia antes de concatenar
if not tabelas_extraidas:
    logging.critical("Falha crítica: Nenhum dado foi retornado da API. Verifique sua conexão ou o status do ONS.")
    exit()

df_consolidado = pd.concat(tabelas_extraidas, ignore_index=True)
logging.info(f"Extração finalizada com sucesso. Total de linhas: {len(df_consolidado)}.")

# ==============================================================================
# PASSO 2: ENGENHARIA DE DADOS E LIMPEZA
# ==============================================================================
logging.info("Aplicando tipagem e classificação sazonal aos dados brutos.")

df_consolidado['dat_referencia'] = pd.to_datetime(df_consolidado['dat_referencia'])
df_consolidado['val_cargaglobal'] = pd.to_numeric(df_consolidado['val_cargaglobal'], errors='coerce')
df_consolidado['Ano'] = df_consolidado['dat_referencia'].dt.year
df_consolidado['Estacao'] = df_consolidado['dat_referencia'].apply(classificar_estacao)

# ==============================================================================
# PASSO 3: CÁLCULOS ESTATÍSTICOS E EXPORTAÇÃO EXCEL
# ==============================================================================
logging.info("Calculando matriz de evolução sazonal e extremos de consumo.")

tabela_comparativa = df_consolidado.groupby(['Ano', 'Estacao'])['val_cargaglobal'].mean().reset_index()
tabela_comparativa.rename(columns={'val_cargaglobal': 'Média (MWmed)'}, inplace=True)
tabela_comparativa['Média (MWmed)'] = tabela_comparativa['Média (MWmed)'].round(2)

df_analise = tabela_comparativa.pivot(index='Estacao', columns='Ano', values='Média (MWmed)')
df_analise['Crescimento 21-23 (%)'] = (((df_analise[2023] / df_analise[2021]) - 1) * 100).round(2)

linha_maior = tabela_comparativa.loc[tabela_comparativa['Média (MWmed)'].idxmax()]
linha_menor = tabela_comparativa.loc[tabela_comparativa['Média (MWmed)'].idxmin()]

resumo_extremos = pd.DataFrame({
    'Métrica': ['Maior Consumo Histórico', 'Menor Consumo Histórico'],
    'Estação': [linha_maior['Estacao'], linha_menor['Estacao']],
    'Ano': [linha_maior['Ano'], linha_menor['Ano']],
    'Valor (MWmed)': [linha_maior['Média (MWmed)'], linha_menor['Média (MWmed)']],
    'Crescimento no Período (%)': [
        f"{df_analise.loc[linha_maior['Estacao'], 'Crescimento 21-23 (%)']}%",
        f"{df_analise.loc[linha_menor['Estacao'], 'Crescimento 21-23 (%)']}%"
    ]
})

arquivo_saida = 'Analise_Eneva_Pedro.xlsx'
with pd.ExcelWriter(arquivo_saida) as writer:
    tabela_comparativa.to_excel(writer, sheet_name='Medias_Anuais', index=False)
    df_analise.to_excel(writer, sheet_name='Crescimento_Delta')
    resumo_extremos.to_excel(writer, sheet_name='Maximos_e_Minimos', index=False)

logging.info(f"Relatório Excel gerado e salvo como: {arquivo_saida}")

# Exibição no terminal para validação da banca
print("\n" + "="*50)
print("RESUMO EXECUTIVO: MÁXIMOS E MÍNIMOS")
print("="*50)
print(resumo_extremos.to_string(index=False))

print("\n" + "="*50)
print("MATRIZ DE CRESCIMENTO PERCENTUAL (2021-2023)")
print("="*50)
print(df_analise.to_string())
print("\n")

# Exportação Estética para Excel
writer = pd.ExcelWriter('Analise_Eneva_Pedro.xlsx', engine='xlsxwriter')
tabela_comparativa.to_excel(writer, sheet_name='Medias_Anuais', index=False)
df_analise.to_excel(writer, sheet_name='Crescimento_Delta')
resumo_extremos.to_excel(writer, sheet_name='Maximos_e_Minimos', index=False)

workbook  = writer.book

# Criando um formato: Azul marinho (Eneva), Negrito e Bordas
header_format = workbook.add_format({
    'bold': True,
    'fg_color': '#1F4E78',
    'font_color': 'white',
    'border': 1
})

# Aplicando o formato e ajustando colunas
for sheet in writer.sheets:
    worksheet = writer.sheets[sheet]
    worksheet.set_column('A:E', 20) # Colunas largas para não cortar texto
    # Reescreve o cabeçalho com o novo estilo
    for col_num, value in enumerate(tabela_comparativa.columns.values):
        worksheet.write(0, col_num, value, header_format)

writer.close()

# ==============================================================================
# PASSO 4: VISUALIZAÇÃO DE DADOS (REQUISITO 5)
# ==============================================================================
logging.info("Renderizando gráfico de tendência (Requisito 5)...")

df_grafico = df_analise.drop(columns=['Crescimento 21-23 (%)']).transpose()
plt.figure(figsize=(11, 6))

for estacao in df_grafico.columns:
    plt.plot(df_grafico.index, df_grafico[estacao], marker='o', label=estacao, linewidth=2.5, markersize=8)

plt.title('Evolução do Consumo Médio por Estação (2021-2023)', fontsize=14, fontweight='bold', pad=20)
plt.ylabel('Carga Média (MWmed)', fontsize=12)
plt.xlabel('Ano', fontsize=12)
plt.xticks([2021, 2022, 2023])
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Estações', bbox_to_anchor=(1.02, 1), loc='upper left')

plt.tight_layout()
plt.savefig('grafico_comparativo_anual.png', dpi=300)
logging.info("Gráfico processado e salvo.")

logging.info("Pipeline Eneva finalizado com sucesso.")
plt.show()